/* empty css                      */import{a as S,S as q,i as c}from"./assets/vendor-BK2FPhdO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const B="54780103-b22ef04994d9984d9528d48dd",M="https://pixabay.com/api/";async function u(o,t=1){return(await S.get(M,{params:{key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const f=document.querySelector(".gallery"),l=document.querySelector(".loader"),m=document.querySelector(".load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const t=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:a,comments:b,downloads:w})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img src="${s}" alt="${e}" loading="lazy" />
          <div class="info">
            <div class="info-item"><b>Likes</b><p>${r}</p></div>
            <div class="info-item"><b>Views</b><p>${a}</p></div>
            <div class="info-item"><b>Comments</b><p>${b}</p></div>
            <div class="info-item"><b>Downloads</b><p>${w}</p></div>
          </div>
        </a>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function E(){f.innerHTML=""}function y(){l.classList.add("is-active"),l.classList.remove("is-hidden")}function g(){l.classList.remove("is-active"),l.classList.add("is-hidden")}function h(){m.classList.remove("is-hidden")}function L(){m.classList.add("is-hidden")}let d="",n=1;const v=15,P=document.querySelector(".form"),O=document.querySelector(".load-more");P.addEventListener("submit",async o=>{o.preventDefault();const t=o.currentTarget.elements["search-text"].value.trim();if(t){d=t,n=1,E(),L(),y();try{const s=await u(d,n);if(s.hits.length===0){c.error({message:"Sorry, no images found matching your query."});return}p(s.hits),s.totalHits>v&&h()}catch{c.error({message:"Error fetching data!"})}finally{g(),o.target.reset()}}});O.addEventListener("click",async()=>{n+=1,L(),y();try{const o=await u(d,n);p(o.hits);const t=document.querySelector(".gallery-item");if(t){const{height:i}=t.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}const s=Math.ceil(o.totalHits/v);n>=s?c.info({message:"We're sorry, but you've reached the end of search results."}):h()}catch{c.error({message:"Error loading more images!"})}finally{g()}});
//# sourceMappingURL=index.js.map
